# Generated by Django 2.2.6 on 2019-12-20 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='residence',
            name='zipcode',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workplace',
            name='zipcode',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='residence',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='employer_email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='employer_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='employer_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
