# Generated by Django 2.2.6 on 2019-12-24 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_residence_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='residence',
            name='static_map_url',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='residence',
            name='static_streetview_url',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workplace',
            name='static_map_url',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workplace',
            name='static_streetview_url',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
    ]
